import React from "react";
// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <title>Post Black Belt</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
